configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/envgs.yaml # envgs model configuration
    - configs/datasets/envgs/room.yaml # dataset usage configuration

model_cfg:
    supervisor_cfg:
        perc_loss_start_iter: 45000 # less iterations for faster training

runner_cfg:
    epochs: 120
    eval_ep: 30

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
