configs:
    - configs/datasets/nerf-casting/nerf-casting.yaml

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        data_root: data/datasets/nerf-casting/toaster
        view_sample: [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23,
                      25, 26, 27, 28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45,
                      46, 47, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 65, 66, 67,
                      68, 69, 70, 71, 73, 74, 75, 76, 77, 78, 79, 81, 82, 83, 84, 85, 86, 87, 89,
                      90, 91, 92, 93, 94, 95, 97, 98, 99, 100, 101, 102, 103, 105, 106, 107, 108,
                      109, 110, 111, 113, 114, 115, 116, 117, 118, 119, 121, 122, 123, 124, 125,
                      126, 127, 129, 130, 131, 132, 133, 134, 135, 137, 138, 139, 140, 141, 142,
                      143, 145, 146, 147, 148, 149, 150, 151, 153, 154, 155, 156, 157, 158, 159,
                      161, 162, 163, 164, 165, 166, 167, 169, 170, 171, 172, 173, 174, 175, 177,
                      178, 179, 180, 181, 182, 183, 185, 186, 187, 188, 189, 190, 191, 193, 194,
                      195, 196, 197, 198, 199, 201, 202, 203, 204, 205, 206, 207, 209, 210, 211,
                      212, 213, 214, 215, 217, 218, 219, 220, 221, 222, 223, 225, 226, 227, 228,
                      229, 230, 231, 233, 234, 235, 236, 237, 238, 239, 241, 242, 243, 244, 245,
                      246, 247, 249, 250, 251, 252, 253, 254, 255, 257, 258, 259, 260, 261, 262,
                      263, 265, 266, 267, 268, 269, 270, 271, 273, 274, 275, 276, 277, 278, 279,
                      281, 282, 283, 284, 285, 286, 287, 289, 290, 291, 292, 293, 294, 295, 297,
                      298, 299, 300, 301, 302, 303, 305, 306, 307, 308, 309, 310, 311, 313, 314,
                      315, 316, 317, 318, 319, 321, 322, 323, 324, 325, 326, 327, 329, 330, 331,
                      332, 333, 334, 335, 337, 338, 339, 340, 341, 342, 343, 345, 346, 347]

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
        view_sample: [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136,
                      144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256,
                      264, 272, 280, 288, 296, 304, 312, 320, 328, 336, 344]

model_cfg:
    sampler_cfg:
        preload_gs: data/datasets/nerf-casting/toaster/sparse/0/points3D.ply
        spatial_scale: 5.333385944366455
        # Environment Gaussian
        env_preload_gs: data/datasets/nerf-casting/toaster/envs/points3D.ply
        env_bounds: [[-15.275330721926242, -5.959935539638103, -5.124253128989539], [9.598054620897013, 12.531957972964317, 14.065504243449332]]
