configs:
    - configs/datasets/shiny_blender/shiny_blender.yaml

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        data_root: data/datasets/refnerf/shiny_blender/helmet/train
        view_sample: [0, null, 1]

val_dataloader_cfg:
    dataset_cfg:
        data_root: data/datasets/refnerf/shiny_blender/helmet/test
        view_sample: [0, null, 1]

model_cfg:
    sampler_cfg:
        preload_gs: data/datasets/refnerf/shiny_blender/helmet/points/pcds/points3d.ply
        spatial_scale: 5.202147674560547
        # Environment Gaussian
        env_preload_gs: data/datasets/refnerf/shiny_blender/helmet/points/envs/points3d.ply
        env_bounds: [[-50.0, -50.0, -50.0], [50.0, 50.0, 50.0]]
